package com.evan.floatscreenrecorder.provider;

import static android.content.Context.NOTIFICATION_SERVICE;

import static com.evan.floatscreenrecorder.common.constant.Constants.FAB_CLOSE_ACTION;
import static com.evan.floatscreenrecorder.common.constant.Constants.NOTIFICATIONS;
import static com.evan.floatscreenrecorder.common.constant.Constants.NOTIFICATION_RECODE_CHANNEL_ID;
import static com.evan.floatscreenrecorder.common.constant.Constants.NOTIFICATION_RECODE_CHANNEL_NAME;
import static com.evan.floatscreenrecorder.common.constant.Constants.PERMISSION_LIST;
import static com.evan.floatscreenrecorder.common.constant.Constants.PERMISSION_TYPE;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.Application;
import android.app.KeyguardManager;
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Context;
import android.content.Intent;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;

import androidx.annotation.NonNull;
import androidx.lifecycle.DefaultLifecycleObserver;
import androidx.lifecycle.LifecycleObserver;
import androidx.lifecycle.LifecycleOwner;
import androidx.lifecycle.ProcessLifecycleOwner;

import com.evan.floatscreenrecorder.EvanSDK;
import com.evan.floatscreenrecorder.common.util.DeviceUtils;
import com.evan.floatscreenrecorder.common.util.ToastUtil;
import com.evan.floatscreenrecorder.fab.manager.FABManager;
import com.evan.floatscreenrecorder.fab.service.FABService;
import com.evan.floatscreenrecorder.record.activity.PermissionActivity;
import com.evan.floatscreenrecorder.record.manager.RecordingManager;

public class SDKProvider extends ContentProvider implements LifecycleObserver {

    // 使用 Application Context 避免記憶體洩漏
    private static Context sApplicationContext;

    private static int m_activityCount;

    private static boolean m_fromBackground = false;
    private static boolean isScreenOff = false;

    @Override
    public boolean onCreate() {
        Context context = getContext();
        if (context != null) {
            // 使用 getApplicationContext() 來避免記憶體洩漏
            sApplicationContext = context.getApplicationContext();
        }
        
        getNotificationPermission();
        ToastUtil.init(sApplicationContext);

        ProcessLifecycleOwner.get().getLifecycle().addObserver(new DefaultLifecycleObserver() {
            @Override
            public void onStart(@NonNull LifecycleOwner owner) {
                // 應用程式進入前景
                if (!m_fromBackground) {
                    return;
                }

                // 延遲是因為回到應用時，如果遇到橫豎切換，過早顯示懸浮按鈕，部分裝置會一瞬間看到懸浮視窗在錯誤的位置 //
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        //  Service is generated by SDKProvider  //
                        FABManager.setFromExternalInterface(true);
                        if (sApplicationContext != null) {
                            sApplicationContext.startService(new Intent(sApplicationContext, FABService.class));
                        }
                        m_fromBackground = false;
                    }
                }, 500);
            }

            @Override
            public void onStop(@NonNull LifecycleOwner owner) {
                // 應用程式進入背景
                if (!FABManager.isServiceAlive()) {
                    return;
                }

                // 發送關閉懸浮視窗的事件 //
                m_fromBackground = true;
                Intent startIntent = new Intent(FAB_CLOSE_ACTION);
                startIntent.setPackage(DeviceUtils.getPackageName(sApplicationContext));
                if (sApplicationContext != null) {
                    sApplicationContext.sendBroadcast(startIntent);
                }

                // 部分手機鎖屏視同onDestroyed，需判斷狀態是否是鎖屏 //
                if (sApplicationContext != null) {
                    KeyguardManager mKeyguardManager = (KeyguardManager) sApplicationContext.getSystemService(Context.KEYGUARD_SERVICE);
                    isScreenOff = mKeyguardManager.inKeyguardRestrictedInputMode();
                }
            }
        });

        if (sApplicationContext instanceof Application) {
            ((Application) sApplicationContext).registerActivityLifecycleCallbacks(new Application.ActivityLifecycleCallbacks() {
                @Override
                public void onActivityCreated(Activity activity, Bundle bundle) {
                    m_activityCount++;
                }

                @Override
                public void onActivityStarted(@NonNull Activity activity) {

                }

                @Override
                public void onActivityResumed(@NonNull Activity activity) {

                }

                @Override
                public void onActivityPaused(@NonNull Activity activity) {

                }

                @Override
                public void onActivityStopped(@NonNull Activity activity) {

                }

                @Override
                public void onActivitySaveInstanceState(@NonNull Activity activity, @NonNull Bundle outState) {

                }

                @Override
                public void onActivityDestroyed(Activity activity) {
                    m_activityCount--;
                    if (m_activityCount > 0) {
                        return;
                    }

                    // 部分手機鎖屏視同onDestroyed，需判斷狀態是否是鎖屏 //
                    if (sApplicationContext != null) {
                        KeyguardManager mKeyguardManager = (KeyguardManager) sApplicationContext.getSystemService(Context.KEYGUARD_SERVICE);
                        isScreenOff = mKeyguardManager.inKeyguardRestrictedInputMode();
                    }

                    if (isScreenOff) {
                        // 當前為鎖屏，不中斷錄影 //
                        return;
                    }

                    // 當前在錄影，中斷錄影 //
                    if (RecordingManager.getIsRecording()) {
                        EvanSDK.setLoopRecordingStatus(sApplicationContext, false, null);
                    }
                }
            });
        }
        return true;
    }

    @Override
    public Cursor query(Uri uri, String[] strings, String s, String[] strings1, String s1) {
        return null;
    }

    @Override
    public String getType(Uri uri) {
        return null;
    }

    @Override
    public Uri insert(Uri uri, ContentValues contentValues) {
        return null;
    }

    @Override
    public int delete(Uri uri, String s, String[] strings) {
        return 0;
    }

    @Override
    public int update(Uri uri, ContentValues contentValues, String s, String[] strings) {
        return 0;
    }

    public static boolean isFromBackground() {
        return m_fromBackground;
    }

    /**
     * Get Notification Permission
     */
    private void getNotificationPermission() {
        if (sApplicationContext == null) {
            return;
        }
        
        // SDK 33 但 在APP 為 32或更低版本目標平台
        // 將createNotificationChannel 提前執行來觸發系統通知權限對話框。
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel notificationChannel = new NotificationChannel(
                    NOTIFICATION_RECODE_CHANNEL_ID,
                    NOTIFICATION_RECODE_CHANNEL_NAME,
                    NotificationManager.IMPORTANCE_LOW
            );

            notificationChannel.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);

            NotificationManager notificationManager = (NotificationManager) sApplicationContext.getSystemService(NOTIFICATION_SERVICE);
            notificationManager.createNotificationChannel(notificationChannel);
        }

        if (Build.VERSION.SDK_INT >= 33) {
            // 為初次開啟時
            String[] permissionStrings = new String[]{"POST_NOTIFICATIONS"};
            goToActivity(sApplicationContext, PermissionActivity.class, permissionStrings, NOTIFICATIONS);
        }
    }

    /**
     * Go To Activity
     */
    private static void goToActivity(Context context, Class<?> cls, String[] strings, String type) {
        if (context == null) {
            return;
        }
        
        Intent intent = new Intent(context, cls);
        if (null != strings) {
            intent.putExtra(PERMISSION_LIST, strings);
        }

        if (null != strings) {
            intent.putExtra(PERMISSION_TYPE, type);
        }

        // android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(intent);
    }
}
