package com.evan.floatscreenrecorder.fab.activity;

import static com.evan.floatscreenrecorder.common.constant.Constants.FAB_DISPLAY_ACTION;
import static com.evan.floatscreenrecorder.common.constant.Constants.FAB_HIDE_ACTION;
import static com.evan.floatscreenrecorder.common.constant.Constants.RECORD_USER_REFUSE_MSG;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.util.Log;

import com.evan.floatscreenrecorder.common.constant.RecordingConstants;
import com.evan.floatscreenrecorder.common.manager.CallbackManager;
import com.evan.floatscreenrecorder.common.util.DeviceUtils;
import com.evan.floatscreenrecorder.common.util.ToastUtil;
import com.evan.floatscreenrecorder.fab.manager.FABManager;
import com.evan.floatscreenrecorder.fab.manager.FABScreenManager;
import com.evan.floatscreenrecorder.fab.service.FABService;

import org.jetbrains.annotations.Nullable;

/**
 * Created by Evan on 2021/11/9.
 * <p>
 * Description：
 *
 */

public class FABActivity extends Activity {

    /**
     * Construct
     */
    private final int FLOATING_PERMISSION_REQUEST_CODE = RecordingConstants.FLOATING_PERMISSION_REQUEST_CODE;
    private AlertDialog permissionDialog;


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // init FABScreenManager to Get Screen Size //
        FABScreenManager.init(this);
        showFloatingButton();
    }


    //=============================================================
    /**
     * Show Floating Button
     */
    //=============================================================
    private void showFloatingButton() {

        if (!Settings.canDrawOverlays(FABActivity.this)) {
            setPermissionDialog();
            permissionDialog.show();
            return;
        }


        stopService(new Intent(this, FABService.class));
        startService(new Intent(this, FABService.class));

        //  Service is generated by FABActivity  //
        FABManager.setFromExternalInterface(false);

        finish();

    }

    //=============================================================
    /**
     * Set Permission Dialog
     */
    //=============================================================
    private void setPermissionDialog() {
        permissionDialog = new AlertDialog.Builder(FABActivity.this).setMessage("需要懸浮權限").setNegativeButton("取消", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                CallbackManager.getNativeFloatingButtonCallback().onError(RECORD_USER_REFUSE_MSG);
                finish();
                overridePendingTransition(RecordingConstants.TRANSITION_NO_ANIMATION, RecordingConstants.TRANSITION_NO_ANIMATION);
            }

        }).setPositiveButton("確認", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                startActivityForResult(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:" + getPackageName())), FLOATING_PERMISSION_REQUEST_CODE);
            }
        }).setCancelable(false).create();
    }


    //=============================================================
    /**
     * Show Toast
     */
    //=============================================================
    private void showToast(String msg) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                // 使用當前 Activity 的 Context，避免依賴全域 Context
                ToastUtil.showToast(FABActivity.this, msg);
            }
        });
    }


    //=============================================================
    /**
     * Set Floating Button Display
     */
    //=============================================================
    public static void setFloatingButtonDisplay(Activity activity, boolean display) {
        Intent startIntent;
        if (display) {
            startIntent = new Intent(FAB_DISPLAY_ACTION);
        } else {
            startIntent = new Intent(FAB_HIDE_ACTION);
        }
        startIntent.setPackage(DeviceUtils.getPackageName(activity));
        activity.sendBroadcast(startIntent);
    }


    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (!Settings.canDrawOverlays(FABActivity.this)) {
            permissionDialog.show();
            Log.e("Evan", "canDrawOverlays 無效");
            return;
        }



        stopService(new Intent(this, FABService.class));
        startService(new Intent(this, FABService.class));
        finish();
    }


    @Override
    protected void onDestroy() {
        if (null != permissionDialog) {
            permissionDialog.dismiss();
        }

        super.onDestroy();
    }
}

